services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq2
    hostname: rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scripts
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq2:5672/
    volumes:
      - ./songs:/app/finall-data/songs
      - ./data:/app/finall-data/data